export const PRAYERS = [
  {
    id: 'rozaniec',
    name: 'Różaniec Święty',
    category: 'rozaniec',
    emoji: '',
    description: 'Najpopularniejsza modlitwa kontemplacyjna chrześcijaństwa, polegająca na rozważaniu kluczowych wydarzeń z życia Jezusa i Maryi. Modlitwa ta jest potężnym narzędziem duchowym, które pomaga wyciszyć serce i odnaleźć pokój w Bożej obecności.',
    history: 'Tradycja przypisuje powstanie różańca św. Dominikowi, któremu miała go objawić Matka Boża w XIII wieku. Przez wieki forma ta ewoluowała, aż do ostatecznego zatwierdzenia przez papieża św. Piusa V w XVI wieku po zwycięstwie pod Lepanto.',
    intentions: ['ogólne', 'pokój', 'rodzina', 'nawrócenie'],
    duration: '20-45 min',
    days: null,
    intro: 'Różaniec to modlitwa kontemplacyjna, podczas której rozważamy tajemnice z życia Jezusa i Maryi.',
    parts: [
      { title: 'Wierzę w Boga', text: 'Wierzę w Boga, Ojca wszechmogącego, Stworzyciela nieba i ziemi. I w Jezusa Chrystusa, Syna Jego jedynego, Pana naszego, który się począł z Ducha Świętego, narodził się z Maryi Panny, umęczon pod Ponckim Piłatem, ukrzyżowan, umarł i pogrzebion. Zstąpił do piekieł, trzeciego dnia zmartwychwstał. Wstąpił na niebiosa, siedzi po prawicy Boga Ojca wszechmogącego. Stamtąd przyjdzie sądzić żywych i umarłych. Wierzę w Ducha Świętego, święty Kościół powszechny, świętych obcowanie, grzechów odpuszczenie, ciała zmartwychwstanie, żywot wieczny. Amen.' },
      { title: 'Ojcze Nasz', text: 'Ojcze nasz, któryś jest w niebie, święć się imię Twoje, przyjdź królestwo Twoje, bądź wola Twoja jako w niebie, tak i na ziemi. Chleba naszego powszedniego daj nam dzisiaj, i odpuść nam nasze winy, jako i mi odpuszczamy naszym winowajcom. I nie wódź nas na pokuszenie, ale nas zbaw ode złego. Amen.' },
      { title: 'Zdrowaś Maryjo', text: 'Zdrowaś Maryjo, łaski pełna, Pan z Tobą, błogosławionaś Ty między niewiastami i błogosławiony owoc żywota Twojego, Jezus. Święta Maryjo, Matko Boża, módl się za nami grzesznymi teraz i w godzinę śmierci naszej. Amen.' },
      { title: 'Chwała Ojcu', text: 'Chwała Ojcu i Synowi, i Duchowi Świętemu. Jak była na początku, teraz i zawsze, i na wieki wieków. Amen.' },
      { title: 'Modlitwa fatimska', text: 'O mój Jezu, przebacz nam nasze grzechy, zachowaj nas od ognia piekielnego, zaprowadź wszystkie dusze do nieba i dopomóż szczególnie tym, którzy najbardziej potrzebują Twojego miłosierdzia.' },
      { title: 'Pod Twoją obronę', text: 'Pod Twoją obronę uciekamy się, święta Boża Rodzicielko, naszymi prośbami racz nie gardzić w potrzebach naszych, ale od wszelakich złych przygód racz nas zawsze wybawiać, Panno chwalebna i błogosławiona. O Pani nasza, Orędowniczko nasza, Pośredniczko nasza, Pocieszycielko nasza. Z Synem swoim nas pojednaj, Synowi swojemu nas polecaj, swojemu Synowi nas oddawaj. Amen.' }
    ],
    mysteries: [
      { name: 'Tajemnice Radosne (pon./sob.)', items: ['Zwiastowanie Najświętszej Maryi Pannie','Nawiedzenie Świętej Elżbiety','Narodzenie Pana Jezusa','Ofiarowanie Pana Jezusa w Świątyni','Znalezienie Pana Jezusa w Świątyni'] },
      { name: 'Tajemnice Światła (czw.)', items: ['Chrzest Pana Jezusa w Jordanie','Objawienie się Jezusa na Weselu w Kanie','Głoszenie Królestwa Bożego','Przemienienie Pańskie','Ustanowienie Eucharystii'] },
      { name: 'Tajemnice Bolesne (wt./pt.)', items: ['Modlitwa Pana Jezusa w Ogrójcu','Biczowanie Pana Jezusa','Ukoronowanie Pana Jezusa cierniem','Droga Krzyżowa Pana Jezusa','Śmierć Pana Jezusa na Krzyżu'] },
      { name: 'Tajemnice Chwalebne (śr./nd.)', items: ['Zmartwychwstanie Pana Jezusa','Wniebowstąpienie Pana Jezusa','Zesłanie Ducha Świętego','Wniebowzięcie Najświętszej Maryi Panny','Ukoronowanie Najświętszej Maryi Panny'] },
    ]
  },
  {
    id: 'koronka',
    name: 'Koronka do Miłosierdzia Bożego',
    category: 'koronka',
    emoji: '',
    description: 'Modlitwa o Boże miłosierdzie dla nas i całego świata. Jest to wołanie o litość i przebaczenie, opierające się na zasługach bolesnej męki Chrystusa.',
    history: 'Została podyktowana przez samego Pana Jezusa św. siostrze Faustynie Kowalskiej w Wilnie, w dniach 13-14 września 1935 roku, jako modlitwa na uśmierzenie gniewu Bożego.',
    intentions: ['miłosierdzie', 'grzesznicy', 'konający', 'trudne sytuacje'],
    duration: '15-20 min',
    days: null,
    intro: 'Odmawiamy ją na zwykłym różańcu.',
    parts: [
      { title: 'Znak Krzyża', text: 'W imię Ojca i Syna, i Ducha Świętego. Amen.' },
      { title: 'Modlitwy wstępne', text: 'Ojcze nasz... Zdrowaś Maryjo... Wierzę w Boga...' },
      { title: 'Na dużych paciorkach', text: 'Ojcze Przedwieczny, ofiaruję Ci Ciało i Krew, Duszę i Bóstwo najmilszego Syna Twojego, a Pana naszego Jezusa Chrystusa, na przebłaganie za grzechy nasze i całego świata.' },
      { title: 'Na małych paciorkach (10 razy)', text: 'Dla Jego bolesnej Męki, miej miłosierdzie dla nas i całego świata.' },
      { title: 'Doksologia', text: 'Święty Boże, Święty Mocny, Święty Nieśmiertelny, zmiłuj się nad nami i nad całym światem. (3 razy)' },
      { title: 'Aklamacja', text: 'O Krwi i Wodo, któraś wypłynęła z Najświętszego Serca Jezusowego jako zdrój Miłosierdzia dla nas – ufam Tobie! (3 razy)' },
      { title: 'Zakończenie', text: 'Jezu, ufam Tobie! (3 razy)' }
    ],
    mysteries: []
  },
  {
    id: 'aniol-panski',
    name: 'Anioł Pański',
    category: 'maryjna',
    emoji: '',
    description: 'Tradycyjna modlitwa upamiętniająca Wcielenie Syna Bożego i zwiastowanie Najświętszej Maryi Pannie. Przypomina o pokorze Maryi i Bożym planie zbawienia.',
    history: 'Początki modlitwy sięgają XI wieku, kiedy zaczęto dzwonić na wieczorną modlitwę ku czci Maryi. Z czasem dodano modlitwę ranną i południową, tworząc obecny cykl trzech modlitw dziennie.',
    intentions: ['wiara', 'pokora', 'codzienność'],
    duration: '3 min',
    days: null,
    intro: 'Anioł Pański odmawiamy trzykrotnie w ciągu dnia: o godz. 6:00, 12:00 i 18:00.',
    parts: [
      { title: 'Zwiastowanie', text: 'Anioł Pański zwiastował Pannie Maryi. I poczęła z Ducha Świętego.' },
      { title: 'Zdrowaś Maryjo', text: 'Zdrowaś Maryjo...' },
      { title: 'Oto ja służebnica', text: 'Oto ja służebnica Pańska. Niech mi się stanie według słowa Twego.' },
      { title: 'Zdrowaś Maryjo', text: 'Zdrowaś Maryjo...' },
      { title: 'Słowo stało się Ciałem', text: 'A Słowo stało się Ciałem. I zamieszkało między nami.' },
      { title: 'Zdrowaś Maryjo', text: 'Zdrowaś Maryjo...' },
      { title: 'Wezwanie', text: 'Módl się za nami, święta Boża Rodzicielko. Abyśmy się stali godnymi obietnic Chrystusowych.' },
      { title: 'Modlitwa', text: 'Módlmy się: Łaskę Twoją, prosimy Cię, Panie, racz wlać w serca nasze, abyśmy, którzy za zwiastowaniem anielskim Wcielenie Chrystusa, Syna Twego, poznali, przez mękę Jego i krzyż do chwały zmartwychwstania byli doprowadzeni. Przez Chrystusa, Pana naszego. Amen.' }
    ],
    mysteries: []
  },
  {
    id: 'litania-loretanska',
    name: 'Litania Loretańska',
    category: 'litania',
    emoji: '',
    description: 'Jedna z najpiękniejszych modlitw błagalnych do Najświętszej Maryi Panny, zawierająca liczne tytuły i wezwania sławiące Jej cnoty i rolę w historii zbawienia.',
    history: 'Jej nazwa pochodzi od włoskiego miasta Loreto, gdzie była śpiewana już w XVI wieku. Została oficjalnie zatwierdzona przez papieża Sykstusa V w 1587 roku. Przez wieki dodawano do niej kolejne wezwania, jak np. "Królowo Pokoju" czy "Matko Miłosierdzia".',
    intentions: ['wstawiennictwo Maryi', 'ochrona', 'rodzina', 'pocieszenie'],
    duration: '10 min',
    days: null,
    intro: 'Litania Loretańska to rytmiczne wezwanie do Maryi, naszej Matki i Królowej.',
    parts: [
      { title: 'Kyrie elejson', text: 'Kyrie, elejson. Chryste, elejson. Kyrie, elejson. Chryste, usłysz nas. Chryste, wysłuchaj nas.' },
      { title: 'Inwokacje Trynitarne', text: 'Ojcze z nieba, Boże, zmiłuj się nad nami. Synu, Odkupicielu świata, Boże, zmiłuj się nad nami. Duchu Święty, Boże, zmiłuj się nad nami. Święta Trójco, jedyny Boże, zmiłuj się nad nami.' },
      { title: 'Wezwania Maryjne', text: 'Święta Maryjo, módl się za nami. Święta Boża Rodzicielko. Święta Panno nad pannami. Matko Chrystusowa. Matko Kościoła. Matko łaski Bożej. Matko miłosierdzia. Matko nadziei. Matko nieskalana. Matko najczystsza. Matko dziewicza. Matko nienaruszona. Matko najmilsza. Matko przedziwna. Matko dobrej rady. Matko Stworzyciela. Matko Zbawiciela. Panno roztropna. Panno czcigodna. Panno sławna. Panno można. Panno łaskawa. Panno wierna. Zwierciadło sprawiedliwości. Stolico mądrości. Przyczyno naszej radości. Przybytku Duchowy. Przybytku chwalebny. Przybytku sławny pobożności. Różo duchowna. Wieżo Dawidowa. Wieżo z kości słoniowej. Domie złoty. Arko przymierza. Bramo niebieska. Gwiazdo zaranna. Uzdrowienie chorych. Ucieczko grzesznych. Pocieszycielko migrantów. Pocieszycielko strapionych. Wspomożenie wiernych. Królowo Aniołów. Królowo Patriarchów. Królowo Proroków. Królowo Apostołów. Królowo Męczenników. Królowo Wyznawców. Królowo Dziewic. Królowo wszystkich Świętych. Królowo bez zmazy pierworodnej poczęta. Królowo wniebowzięta. Królowo Różańca świętego. Królowo rodzin. Królowo pokoju. Królowo Polski.' },
      { title: 'Baranku Boży', text: 'Baranku Boży, który gładzisz grzechy świata, przepuść nam, Panie. Baranku Boży, który gładzisz grzechy świata, wysłuchaj nas, Panie. Baranku Boży, który gładzisz grzechy świata, zmiłuj się nad nami.' },
      { title: 'Modlitwa końcowa', text: 'Módl się za nami, święta Boża Rodzicielko. Abyśmy się stali godnymi obietnic Chrystusowych. Módlmy się: Panie, nasz Boże, daj nam, sługom swoim, cieszyć się trwałym zdrowiem duszy i ciała, i za wstawiennictwem Najświętszej Maryi, zawsze Dziewicy, uwolnij nas od doczesnych utrapień i obdarz wieczną radością. Przez Chrystusa, Pana naszego. Amen.' }
    ],
    mysteries: []
  },
  {
    id: 'nowenna-pompejanska',
    name: 'Nowenna Pompejańska',
    category: 'nowenna',
    emoji: '',
    description: 'Nazywana "nowenną nie do odparcia". Jest to 54-dniowe nabożeństwo różańcowe, wymagające ogromnej wytrwałości, ale przynoszące niezwykłe owoce duchowe.',
    history: 'Została rozpropagowana przez bł. Bartolo Longo, byłego kapłana szatana, który nawrócił się i poświęcił życie szerzeniu różańca w Pompejach. Maryja obiecała mu, że ktokolwiek odmówi tę nowennę, otrzyma łaski, o które prosi.',
    intentions: ['sprawy beznadziejne', 'nawrócenie', 'uzdrowienie', 'wielkie prośby'],
    duration: '3x Różaniec/dzień',
    days: 54,
    intro: 'Nowenna Pompejańska to 54-dniowy modlitewny maraton różańcowy. Przez pierwsze 27 dni prosimy Maryję w części błagalnej, a przez kolejne 27 dni dziękujemy za otrzymane łaski.',
    parts: [
      { title: 'Część błagalna (Dni 1-27)', text: 'Pomnij, o miłosierna Panno Różańcowa z Pompei, jako nigdy jeszcze nie słyszano, by ktokolwiek z Twoich czcicieli z Twoim Różańcem, wzywający Twej pomocy, został opuszczony. Ślubuję Ci i przyrzekam, że nie przestanę Cię czcić i Twoją chwałę głosić.' },
      { title: 'Część dziękczynna (Dni 28-54)', text: 'Cóż Ci dać mogę, o Królowo pełna miłości? Całe moje życie poświęcam Tobie. Ile mi sił starczy, będę szerzyć cześć Twoją, o Dziewico Różańca Świętego z Pompei, bo gdy Twojej pomocy wezwałem, nawiedziła mnie łaska Boża.' }
    ],
    mysteries: []
  },
  {
    id: 'nowenna-faustyno',
    name: 'Nowenna do Miłosierdzia Bożego',
    category: 'nowenna',
    emoji: '',
    description: 'Dziewięciodniowe przygotowanie do Święta Miłosierdzia. Każdy dzień to inna grupa dusz, które Jezus pragnie zanurzyć w swoim miłosierdziu.',
    history: 'Podyktowana przez Jezusa św. Faustynie w 1937 roku. Jezus prosił, aby przez te dziewięć dni sprowadzać do Jego serca różne grupy ludzi, szczególnie tych najbardziej potrzebujących przebaczenia.',
    intentions: ['miłosierdzie', 'grzesznicy', 'dusze czyśćcowe', 'kapłani'],
    duration: '10 min/dzień',
    days: 9,
    intro: 'Nowenna zaczyna się zazwyczaj w Wielki Piątek.',
    parts: [
      { day: 1, title: 'Dzień 1 - Cała ludzkość', text: 'Dziś sprowadź Mi całą ludzkość, a szczególnie wszystkich grzeszników, i zanurz ich w przepaści miłosierdzia Mojego. Tym samym pocieszysz Mnie w gorzkim smutku, jaki Mi sprawia utrata dusz. Jezu Najmiłosierniejszy, którego właściwością jest nilitować się nad nami i przebaczać nam, nie patrz na grzechy nasze, ale na ufność, jaką mamy w nieskończoną dobroć Twoją.' },
      { day: 2, title: 'Dzień 2 - Dusze kapłańskie', text: 'Dziś sprowadź Mi dusze kapłańskie i dusze zakonne, i zanurz je w niezgłębionym miłosierdziu Moim. One dały Mi moc przetrwania gorzkiej męki, przez nie, jak przez kanały, płynie na ludzkość miłosierdzie Moje. Jezu Najmiłosierniejszy, od którego wszystko, co dobre, pochodzi, pomnóż w nas łaskę, abyśmy godne uczynki miłosierdzia spełniali.' },
      { day: 3, title: 'Dzień 3 - Dusze pobożne', text: 'Dziś sprowadź Mi wszystkie dusze pobożne i wierne, i zanurz je w morzu miłosierdzia Mojego; dusze te pocieszyły Mnie na drodze krzyżowej, były tą kroplą pociechy w morzu goryczy. Jezu Najmiłosierniejszy, który z skarbnicy miłosierdzia Twego wszystkim udzielasz łask Swych bardzo obficie, przyjmij nas do mieszkania najlitościwszego Serca Twego.' },
      { day: 4, title: 'Dzień 4 - Poganie i nieznający Boga', text: 'Dziś sprowadź Mi pogan i tych, którzy Mnie jeszcze nie znają; i o nich myślałem w gorzkiej Swej męce, a przyszła ich gorliwość pocieszyła Serce Moje. Zanurz ich w morzu miłosierdzia Mojego. Jezu Najlitościwszy, który jesteś światłością świata całego, przyjmij do mieszkania najlitościwszego Serca Twego dusze pogan, którzy Cię jeszcze nie znają.' },
      { day: 5, title: 'Dzień 5 - Heretycy i odszczepieńcy', text: 'Dziś sprowadź Mi dusze heretyków i odszczepieńców, i zanurz ich w morzu miłosierdzia Mojego; w gorzkiej męce rozdzierali Mi ciało i Serce, to jest Kościół Mój. Kiedy wracają do jedności z Kościołem, goją się rany Moje i tym sposobem lżą Mękę Moją. Jezu Najmiłosierniejszy, który jesteś dobrocią samą, Ty nie odmawiasz światła proszącym Cię, przyjmij do mieszkania najlitościwszego Serca Twego dusze heretyków i dusze odszczepieńców.' },
      { day: 6, title: 'Dzień 6 - Dusze ciche i pokorne', text: 'Dziś sprowadź Mi dusze ciche i pokorne, i dusze małych dzieci, i zanurz je w miłosierdziu Moim. Dusze te są najwięcej podobne do Serca Mojego, one krzepiły Mnie w gorzkiej konania męce; widziałem je jako ziemskich aniołów, którzy będą czuwać u Moich ołtarzy. Jezu Najmiłosierniejszy, któryś sam powiedział: Uczcie się ode Mnie, żem cichy i pokornego serca – przyjmij do mieszkania najlitościwszego Serca Twego dusze ciche i pokorne.' },
      { day: 7, title: 'Dzień 7 - Czciciele Miłosierdzia', text: 'Dziś sprowadź Mi dusze, które szczególnie czczą i wysławiają miłosierdzie Moje, i zanurz je w miłosierdziu Moim. Dusze te najwięcej współczuły męce Mojej i najgłębiej wniknęły w ducha Mojego. One są żywym odbiciem najlitościwszego Serca Mojego. Jezu Najmiłosierniejszy, którego Serce jest miłością samą, przyjmij do mieszkania najlitościwszego Serca Twego dusze, które szczególnie czczą i wysławiają wielkość miłosierdzia Twego.' },
      { day: 8, title: 'Dzień 8 - Dusze czyśćcowe', text: 'Dziś sprowadź Mi dusze, które są w więzieniu czyśćcowym i zanurz je w przepaści miłosierdzia Mojego, niech strumienie krwi Mojej ochłodzą ich upalenie. Wszystkie te dusze są bardzo przeze Mnie umiłowane, wypłacają się Mojej sprawiedliwości; w Twojej mocy jest przynieść im ulgę. Jezu Najmiłosierniejszy, któryś sam powiedział, że miłosierdzia chcesz, oto sprowadzam do mieszkania najlitościwszego Serca Twego dusze czyśćcowe.' },
      { day: 9, title: 'Dzień 9 - Dusze oziębłe', text: 'Dziś sprowadź Mi dusze oziębłe i zanurz je w przepaści miłosierdzia Mojego. Dusze te najboleśniej ranią Serce Moje. Największego obrzydzenia doznała dusza Moja w Ogrójcu od dusz oziębłych. One były powodem, żem wypowiedział te słowa: Ojcze, oddal ten kielich, jeżeli jest wola Twoja. Jezu Najmiłosierniejszy, który jesteś litością samą, wprowadzam do mieszkania najlitościwszego Serca Twego dusze oziębłe.' },
      { title: 'Koronka', text: 'Na zakończenie każdego dnia odmów Koronkę do Miłosierdzia Bożego jako dopełnienie prośby o miłosierdzie dla świata.' }
    ],
    mysteries: []
  },
  {
    id: 'nowenna-rozwiazujaca-wezly',
    name: 'Nowenna do MB Rozwiązującej Węzły',
    category: 'nowenna',
    emoji: '',
    description: 'Niezwykle skuteczna modlitwa o pomoc w rozwikłaniu "węzłów" naszego życia – problemów, które wydają się nie do rozwiązania, nałogów, konfliktów rodzinnych czy długów.',
    history: 'Inspiracją był obraz z XVIII wieku przedstawiający Maryję rozwiązującą węzły na białej wstędze. Modlitwa ta stała się szczególnie znana dzięki papieżowi Franciszkowi, który szerzył ten kult w Argentynie, a potem na całym świecie.',
    intentions: ['trudne sprawy', 'konflikty', 'problemy finansowe', 'nałogi'],
    duration: '20 min/dzień',
    days: 9,
    intro: 'Podczas nowenny prosimy Maryję, by swoimi dłońmi rozwiązała węzły, które duszą naszą duszę i niszczą nasze życie.',
    parts: [
        { day: 1, title: 'Dzień 1', text: 'Matko Najświętsza, Matko pełna miłości, Tobie powierzam węzeł moich problemów. Proszę, rozwiąż go dla chwały Twojego Syna.' },
        { day: 2, title: 'Dzień 2', text: 'Maryjo, Matko najukochańsza, pełna łaski, moje serce zwraca się do Ciebie. Uznaję, że jestem grzesznikiem i potrzebuję Twojej pomocy.' },
        { day: 3, title: 'Dzień 3', text: 'Pani moja, Pośredniczko nasza, Królowo nieba, w Twoich rękach są wszystkie łaski Boże. Rozwiąż ten węzeł w moim życiu.' },
        { day: 4, title: 'Dzień 4', text: 'Święta Matko, Ty rozwiązujesz wszystkie węzły, które nas krępują. Twoje dłonie nigdy nie przestają służyć Twoim dzieciom.' },
        { day: 5, title: 'Dzień 5', text: 'Matko Miłosierdzia, Ty wiesz, jak bardzo cierpię z powodu tego węzła. Proszę, spójrz na mnie z litością.' },
        { day: 6, title: 'Dzień 6', text: 'Królowo Pokoju, uproś nam u swojego Syna pokój serca, którego tak bardzo potrzebujemy.' },
        { day: 7, title: 'Dzień 7', text: 'Matko najczystsza, weź mnie pod swoją opiekę i chroń przed wszelkimi zakusami zła.' },
        { day: 8, title: 'Dzień 8', text: 'Dziewico pełna dobroci, dziękuję Ci za Twoją cierpliwość i miłość, z jaką rozwiązujesz węzły mojej duszy.' },
        { day: 9, title: 'Dzień 9', text: 'Matko Najświętsza, nasza Orędowniczko, dziękuję za wszystkie łaski. Ucz mnie żyć w pokorze i miłości.' }
    ],
    mysteries: []
  },
  {
    id: 'droga-krzyzowa',
    name: 'Droga Krzyżowa',
    category: 'pasja',
    emoji: '',
    description: 'Nabożeństwo pasyjne polegające na rozważaniu męki Jezusa Chrystusa przez 14 stacji. Uczy współcierpienia z Bogiem i pomaga zrozumieć cenę naszego zbawienia.',
    history: 'Tradycja ta wywodzi się z pielgrzymek do Jerozolimy. W średniowieczu, gdy podróż do Ziemi Świętej była trudna, zaczęto budować stacje drogi krzyżowej w Europie, aby wierni mogli duchowo towarzyszyć Jezusowi w Jego ostatniej drodze.',
    intentions: ['pokuta', 'zrozumienie cierpienia', 'nawrócenie', 'wdzięczność'],
    duration: '20-40 min',
    days: null,
    intro: 'Przejdźmy drogą miłości, która nie cofnęła się przed krzyżem.',
    parts: [
      { title: 'Stacja I', text: 'Pan Jezus na śmierć skazany. Kłaniamy Ci się, Chryste, i błogosławimy Tobie. Żeś przez krzyż i mękę swoją świat odkupić raczył. Niewinny Baranek staje przed sądem człowieka. Przyjmuje wyrok z pokorą, wiedząc, że to droga do zbawienia świata.' },
      { title: 'Stacja II', text: 'Pan Jezus bierze krzyż na swoje ramiona. Ciężkie drzewo spoczywa na zranionym ciele. Każdy krok to ból, ale i miłość, która pcha do przodu.' },
      { title: 'Stacja III', text: 'Pierwszy upadek pod krzyżem. Bóg pada na ziemię. Zmęczenie i ciężar grzechów przygniatają Go do prochu, byśmy my mogli z niego powstać.' },
      { title: 'Stacja IV', text: 'Pan Jezus spotyka swą Matkę. Spojrzenie pełne bólu i zrozumienia. Maryja towarzyszy Synowi w najtrudniejszej godzinie.' },
      { title: 'Stacja V', text: 'Szymon z Cyreny pomaga nieść krzyż Jezusowi. Przymuszony, a jednak staje się uczestnikiem zbawczego dzieła. Każdy nasz trud może być pomocą Jezusowi.' },
      { title: 'Stacja VI', text: 'Weronika ociera twarz Jezusowi. Odważny gest miłości w tłumie nienawiści. Jezus pozostawia odbicie swego oblicza w sercu pełnym litości.' },
      { title: 'Stacja VII', text: 'Drugi upadek pod krzyżem. Ponowny ból i upokorzenie. Jezus powstaje, by pokazać, że nigdy nie wolno się poddawać w drodze do celu.' },
      { title: 'Stacja VIII', text: 'Pan Jezus pociesza płaczące niewiasty. "Nie płaczcie nade Mną, ale nad sobą i nad dziećmi waszymi". Wezwanie do prawdziwego żalu za grzechy.' },
      { title: 'Stacja IX', text: 'Trzeci upadek pod krzyżem. Ostatkiem sił. Jezus uczy nas wytrwałości do samego końca, nawet gdy siły całkowicie nas opuszczają.' },
      { title: 'Stacja X', text: 'Pan Jezus z szat obnażony. Ogołocenie z godności. Wszystko oddał za nas, nie zachowując nic dla siebie.' },
      { title: 'Stacja XI', text: 'Pan Jezus przybity do krzyża. Gwoździe przeszywają dłonie i stopy. Miłość przytwierdzona do drewna dla naszego odkupienia.' },
      { title: 'Stacja XII', text: 'Pan Jezus umiera na krzyżu. "Wykonało się". Największa ofiara w dziejach świata staje się faktem.' },
      { title: 'Stacja XIII', text: 'Pan Jezus zdjęty z krzyża. Maryja przyjmuje martwe ciało Syna. Pieta – milcząca skarga i niezłomna wiara.' },
      { title: 'Stacja XIV', text: 'Pan Jezus do grobu złożony. Cisza wielkiej soboty. Ziarno wrzucone w ziemię, które wkrótce wyda owoc zmartwychwstania.' }
    ],
    mysteries: []
  },
  {
    id: 'koronka-duch-swiety',
    name: 'Koronka do Ducha Świętego',
    category: 'koronka',
    emoji: '',
    description: 'Modlitwa o siedem darów Ducha Świętego. Wołanie o ogień miłości, który przemienia serce.',
    history: 'Zatwierdzona przez papieża Leona XIII jako sposób na ożywienie kultu Trzeciej Osoby Boskiej.',
    intentions: ['dary Ducha', 'mądrość', 'ważne wybory'],
    duration: '10 min',
    days: null,
    intro: 'Duchu Święty, natchnij nas.',
    parts: [
      { title: 'Dar Mądrości', text: 'Przyjdź Duchu Mądrości, odciągnij nas od rzeczy ziemskich, a rozpal w nas pragnienie rzeczy niebieskich.' },
      { title: 'Dar Rozumu', text: 'Przyjdź Duchu Rozumu, oświeć nasze umysły, abyśmy poznali prawdy wiary i według nich żyli.' },
      { title: 'Dar Rady', text: 'Przyjdź Duchu Rady, uczyń nas uległymi Twoim natchnieniom, abyśmy zawsze wybierali to, co podoba się Bogu.' },
      { title: 'Dar Męstwa', text: 'Przyjdź Duchu Męstwa, umocnij nas w przeciwnościach i daj siłę do wyznawania wiary bez lęku.' },
      { title: 'Dar Umiejętności', text: 'Przyjdź Duchu Umiejętności, pozwól nam poznać Boga i samych siebie w świetle Jego prawdy.' },
      { title: 'Dar Pobożności', text: 'Przyjdź Duchu Pobożności, uczyń naszą modlitwę miłą Bogu i daj nam serce kochające Ojca Niebieskiego.' },
      { title: 'Dar Bojaźni Bożej', text: 'Przyjdź Duchu Bojaźni Bożej, powstrzymaj nas od wszystkiego złego, co mogłoby nas oddzielić od Twojej miłości.' }
    ],
    mysteries: []
  },
  {
    id: 'nowenna-charbel',
    name: 'Nowenna do św. Charbela',
    category: 'nowenna',
    emoji: '',
    description: 'Modlitwa o uzdrowienie i pomoc za wstawiennictwem wielkiego pustelnika z Libanu. Znana z licznych cudów medycznych i duchowych.',
    history: 'Św. Charbel Makhlouf (1828-1898) spędził życie w milczeniu i ascezie. Po jego śmierci z jego ciała wypływał cudowny olej, który uzdrawiał tysiące ludzi.',
    intentions: ['uzdrowienie', 'zdrowie', 'wiara', 'trudne sytuacje'],
    duration: '10 min/dzień',
    days: 9,
    intro: 'Św. Charbelu, cudotwórco z Libanu, módl się za nami.',
    parts: [
      { day: 1, title: 'Dzień 1', text: 'O cudowny święty Charbelu, Ty z wysokości nieba wstawiasz się za nami. Przychodzę do Ciebie, abyś uprosił mi u Boga łaskę zdrowia duszy i ciała.' },
      { day: 2, title: 'Dzień 2', text: 'Święty Charbelu, naucz nas cierpliwości i zaufania Bogu w każdej chorobie i cierpieniu.' },
      { day: 3, title: 'Dzień 3', text: 'O święty Charbelu, Tyś kochał Boga ponad wszystko, uproś nam dar prawdziwej wiary.' },
      { day: 4, title: 'Dzień 4', text: 'Święty Charbelu, Tyś był wzorem pokory, naucz nas służyć bliźnim z miłością.' },
      { day: 5, title: 'Dzień 5', text: 'O święty Charbelu, Tyś spędził życie na modlitwie, uczyń naszą modlitwę wytrwałą.' },
      { day: 6, title: 'Dzień 6', text: 'Święty Charbelu, pocieszycielu strapionych, otrzyj łzy z naszych oczu.' },
      { day: 7, title: 'Dzień 7', text: 'O święty Charbelu, Tyś był wierny Bogu do końca, pomóż nam wytrwać w dobrym.' },
      { day: 8, title: 'Dzień 8', text: 'Święty Charbelu, orędowniku nasz, nie opuszczaj nas w potrzebie.' },
      { day: 9, title: 'Dzień 9', text: 'O święty Charbelu, dziękujemy za Twoje wstawiennictwo i opiekę.' }
    ],
    mysteries: []
  },
  {
    id: 'nowenna-rita',
    name: 'Nowenna do św. Rity',
    category: 'nowenna',
    emoji: '',
    description: 'Błagalna modlitwa do patronki spraw beznadziejnych. Przynosi pociechę tym, którzy czują, że ich sytuacja nie ma już ludzkiego rozwiązania.',
    history: 'Św. Rita z Cascii otrzymała stygmat ciernia na czole jako znak współcierpienia z Chrystusem. Jest patronką niemożliwych spraw.',
    intentions: ['beznadzieja', 'trudne małżeństwo', 'pokój w rodzinie'],
    duration: '10 min/dzień',
    days: 9,
    intro: 'Święta Rito, róża cierpliwości i miłości, módl się za nami.',
    parts: [
      { day: 1, title: 'Dzień 1', text: 'O potężna święta Rito, Ty, którą Bóg uczynił patronką spraw beznadziejnych, przyjdź mi z pomocą w moim smutku.' },
      { day: 2, title: 'Dzień 2', text: 'Święta Rito, ucz nas wybaczać tym, którzy nas ranią, tak jak Ty wybaczyłaś mordercom swego męża.' },
      { day: 3, title: 'Dzień 3', text: 'O święta Rito, Tyś była cierpliwą żoną i matką, weź w opiekę nasze rodziny.' },
      { day: 4, title: 'Dzień 4', text: 'Święta Rito, Tyś z pokorą przyjęła stygmat ciernia, naucz nas kochać krzyż.' },
      { day: 5, title: 'Dzień 5', text: 'O święta Rito, Tyś była wzorem posłuszeństwa, pomóż nam zawsze pełnić wolę Bożą.' },
      { day: 6, title: 'Dzień 6', text: 'Święta Rito, Tyś nigdy nie straciła nadziei, umocnij naszą ufność w dobroć Boga.' },
      { day: 7, title: 'Dzień 7', text: 'O święta Rito, orędowniczko nasza, uproś nam łaskę, o którą z wiarą prosimy.' },
      { day: 8, title: 'Dzień 8', text: 'Święta Rito, pocieszycielko strapionych, niech Twoja pomoc dotrze do najbardziej potrzebujących.' },
      { day: 9, title: 'Dzień 9', text: 'O święta Rito, dziękujemy za Twoją obecność i wsparcie w naszych trudnościach.' }
    ],
    mysteries: []
  },
  {
    id: 'nowenna-jozef',
    name: 'Nowenna do św. Józefa',
    category: 'nowenna',
    emoji: '',
    description: 'Dziewięciodniowe nabożeństwo do ziemskiego Opiekuna Jezusa. Wzór ojcostwa, opieki nad rodziną i godnej pracy.',
    history: 'Św. Józef, Patron Kościoła powszechnego, jest najpotężniejszym orędownikiem po Maryi.',
    intentions: ['rodzina', 'praca', 'dom', 'dobra śmierć'],
    duration: '10 min/dzień',
    days: 9,
    intro: 'Święty Józefie, stróżu Świętej Rodziny, otocz nas swoją opieką.',
    parts: [
      { day: 1, title: 'Dzień 1', text: 'Święty Józefie, mężu sprawiedliwy, Tyś z wiarą przyjął Boży plan. Pomóż nam zawsze ufać Bogu ponad wszystko.' },
      { day: 2, title: 'Dzień 2', text: 'Święty Józefie, opiekunie Jezusa, naucz nas kochać Go tak, jak Ty Go kochałeś.' },
      { day: 3, title: 'Dzień 3', text: 'O święty Józefie, czysty oblubieńcze Maryi, uproś nam czystość serca i myśli.' },
      { day: 4, title: 'Dzień 4', text: 'Święty Józefie, wzorze pracujących, naucz nas wykonywać nasze obowiązki z miłością do Boga.' },
      { day: 5, title: 'Dzień 5', text: 'O święty Józefie, głowo Świętej Rodziny, weź pod swoją opiekę nasze domy i rodziny.' },
      { day: 6, title: 'Dzień 6', text: 'Święty Józefie, najmężniejszy, daj nam odwagę w wyznawaniu wiary i bronieniu prawdy.' },
      { day: 7, title: 'Dzień 7', text: 'O święty Józefie, nadziejo chorych, przynieś ulgę cierpiącym i umocnij ich siły.' },
      { day: 8, title: 'Dzień 8', text: 'Święty Józefie, patronie umierających, uproś nam łaskę dobrej i świętej śmierci.' },
      { day: 9, title: 'Dzień 9', text: 'O święty Józefie, dziękujemy za Twoje potężne wstawiennictwo i ojcowską troskę.' }
    ],
    mysteries: []
  },
  {
    id: 'koronka-bolesci',
    name: 'Koronka do Siedmiu Boleści Maryi',
    category: 'koronka',
    emoji: '',
    description: 'Modlitwa kontemplacyjna skupiona na współcierpieniu Maryi z Jezusem. Pomaga zrozumieć sens cierpienia i wartość ofiary.',
    history: 'Propagowana przez zakon Serwitów od XIII wieku. Maryja w objawieniach w Kibeho prosiła o ponowne odkrycie tej modlitwy.',
    intentions: ['nawrócenie', 'cierpienie', 'pokój w sercu', 'rodzina'],
    duration: '20 min',
    days: null,
    intro: 'W tej modlitwie rozważamy siedem mieczy boleści, które przeniknęły serce Maryi.',
    parts: [
      { title: 'Boleść 1', text: 'Proroctwo Symeona. Maryjo, współczuję Ci w Twoim bólu, gdy usłyszałaś, że Twoją duszę miecz przeniknie.' },
      { title: 'Boleść 2', text: 'Ucieczka do Egiptu. Maryjo, współczuję Ci w Twoim lęku i trudzie wygnania, gdy chroniłaś Dziecię przed Herodem.' },
      { title: 'Boleść 3', text: 'Zgubienie Jezusa w Świątyni. Maryjo, współczuję Ci w Twoim trwodze, gdy przez trzy dni szukałaś Syna z bólem serca.' },
      { title: 'Boleść 4', text: 'Spotkanie Jezusa na Drodze Krzyżowej. Maryjo, współczuję Ci w Twoim rozdarciu, gdy widziałaś Syna niosącego ciężki krzyż.' },
      { title: 'Boleść 5', text: 'Stanie pod Krzyżem. Maryjo, współczuję Ci w Twojej agonii, gdy patrzyłaś na konanie i śmierć swojego ukochanego Syna.' },
      { title: 'Boleść 6', text: 'Zdjęcie Jezusa z Krzyża. Maryjo, współczuję Ci w Twoim milczącym bólu, gdy martwe ciało Jezusa spoczęło na Twoich kolanach.' },
      { title: 'Boleść 7', text: 'Złożenie Jezusa do Grobu. Maryjo, współczuję Ci w Twojej samotności i nadziei, która przetrwała nawet noc grobu.' }
    ],
    mysteries: []
  },
  {
    id: 'koronka-rany-jezusa',
    name: 'Koronka do Ran Pana Jezusa',
    category: 'koronka',
    emoji: '',
    description: 'Modlitwa skupiona na kontemplacji zbawczych ran Chrystusa. Jezus obiecał, że przez te rany udzieli wszystkiego, o co się Go prosi.',
    history: 'Została przekazana przez Pana Jezusa s. Marii Marcie Chambon (1841-1917). Jezus nazywał ją "apostołką swoich ran".',
    intentions: ['odpuszczenie grzechów', 'ratunek świata', 'zdrowie duszy'],
    duration: '15 min',
    days: null,
    intro: 'Modlitwa ta jest potężnym wynagrodzeniem za grzechy.',
    parts: [
      { title: 'Na dużych paciorkach', text: 'Ojcze Przedwieczny, ofiaruję Ci Rany Pana naszego Jezusa Chrystusa, na uleczenie ran dusz naszych.' },
      { title: 'Na małych paciorkach (10 razy)', text: 'O mój Jezu, przebaczenia i miłosierdzia, przez zasługi Twoich Świętych Ran.' }
    ],
    mysteries: []
  },
  {
    id: 'litania-serce',
    name: 'Litania do Najświętszego Serca Pana Jezusa',
    category: 'litania',
    emoji: '',
    description: 'Błagalna modlitwa do Bożego Serca, źródła wszelkiej pociechy i miłości.',
    history: 'Zatwierdzona przez Leona XIII w 1899 roku.',
    intentions: ['miłość Boża', 'wynagrodzenie', 'pokój'],
    duration: '12 min',
    days: null,
    intro: 'Serce Jezusa, domie Boży i bramo niebios.',
    parts: [
      { title: 'Błagania', text: 'Kyrie, elejson. Chryste, elejson. Kyrie, elejson. Chryste, usłysz nas. Chryste, wysłuchaj nas.' },
      { title: 'Inwokacje Trynitarne', text: 'Ojcze z nieba, Boże, zmiłuj się nad nami. Synu, Odkupicielu świata, Boże, zmiłuj się nad nami. Duchu Święty, Boże, zmiłuj się nad nami. Święta Trójco, jedyny Boże, zmiłuj się nad nami.' },
      { title: 'Wezwania do Serca Jezusa', text: 'Serce Jezusa, Syna Ojca Przedwiecznego, zmiłuj się nad nami. Serce Jezusa, w łonie Matki Dziewicy przez Ducha Świętego utworzone. Serce Jezusa, ze Słowem Bożym istotowo zjednoczone. Serce Jezusa, nieskończonego majestatu. Serce Jezusa, świątynio Boga święta. Serce Jezusa, przybytku Najwyższego. Serce Jezusa, domie Boży i bramo niebios. Serce Jezusa, gorejące ognisko miłości. Serce Jezusa, sprawiedliwości i miłości skarbnico. Serce Jezusa, dobroci i miłości pełne. Serce Jezusa, cnót wszystkich bezdenna głębino. Serce Jezusa, wszelkiej chwały najgodniejsze. Serce Jezusa, królu i zjednoczenie serc wszystkich. Serce Jezusa, w którym są wszystkie skarby mądrości i umiejętności. Serce Jezusa, w którym mieszka cała pełnia Bóstwa. Serce Jezusa, w którym sobie Ojciec bardzo upodobał. Serce Jezusa, z którego pełni wszyscyśmy otrzymali. Serce Jezusa, odwieczne upragnienie świata. Serce Jezusa, cierpliwe i wielkiego miłosierdzia. Serce Jezusa, hojne dla wszystkich, którzy Cię wzywają. Serce Jezusa, źródło życia i świętości. Serce Jezusa, przebłaganie za grzechy nasze. Serce Jezusa, zelżywością napełnione. Serce Jezusa, dla nieprawości naszych starte. Serce Jezusa, aż do śmierci posłuszne. Serce Jezusa, włócznią przebite. Serce Jezusa, źródło wszelkiej pociechy. Serce Jezusa, życie i zmartwychwstanie nasze. Serce Jezusa, pokoju i pojednanie nasze. Serce Jezusa, krwawa ofiaro grzeszników. Serce Jezusa, zbawienie ufających Tobie. Serce Jezusa, nadziejo w Tobie umierających. Serce Jezusa, rozkoszy wszystkich Świętych.' },
      { title: 'Baranku Boży', text: 'Baranku Boży, który gładzisz grzechy świata, przepuść nam, Panie. Baranku Boży, który gładzisz grzechy świata, wysłuchaj nas, Panie. Baranku Boży, który gładzisz grzechy świata, zmiłuj się nad nami.' },
      { title: 'Modlitwa końcowa', text: 'Jezu cichy i pokornego Serca. Uczyń serca nasze według Serca Twego. Módlmy się: Wszechmogący, wieczny Boże, wejrzyj na Serce najmilszego Syna Swego i na chwałę i zadośćuczynienie, jakie Ci w imieniu grzeszników składa; daj się przebłagać tym, którzy Cię proszą o miłosierdzie, i udziel im przebaczenia w imię tegoż Syna Swego, Jezusa Chrystusa, który z Tobą żyje i króluje na wieki wieków. Amen.' }
    ],
    mysteries: []
  },
  {
    id: 'litania-duch-swiety',
    name: 'Litania do Ducha Świętego',
    category: 'litania',
    emoji: '',
    description: 'Modlitwa o wylanie darów Ducha Świętego i przemianę życia.',
    history: 'Tradycyjna modlitwa Kościoła, szczególnie odmawiana przed Zesłaniem Ducha Świętego.',
    intentions: ['światło Ducha', 'odnowa serca', 'wiara'],
    duration: '10 min',
    days: null,
    intro: 'Duchu Święty, Boże, zmiłuj się nad nami.',
    parts: [
      { title: 'Błagania', text: 'Kyrie, elejson. Chryste, elejson. Kyrie, elejson. Chryste, usłysz nas. Chryste, wysłuchaj nas.' },
      { title: 'Wezwania', text: 'Duchu Święty, który od Ojca i Syna pochodzisz, zmiłuj się nad nami. Duchu Święty, który wraz z Ojcem i Synem odbierasz uwielbienie i chwałę. Duchu prawdy i miłości. Duchu mądrości i rozumu. Duchu rady i męstwa. Duchu umiejętności i pobożności. Duchu bojaźni Bożej. Duchu świętości i sprawiedliwości. Duchu pocieszycielu. Duchu łaski i miłosierdzia.' },
      { title: 'Prośby', text: 'Bądź nam miłościw, przepuść nam, Duchu Święty. Bądź nam miłościw, wysłuchaj nas, Duchu Święty. Od wszelkiego złego, wybaw nas, Duchu Święty. Od każdego grzechu. Od pokus szatańskich. Od nieczystości duszy i ciała. Od oziębłości i uporu. Od rozpaczy i domniemania o miłosierdziu Bożym.' },
      { title: 'Zakończenie', text: 'Baranku Boży, który gładzisz grzechy świata, ześlij nam Ducha Świętego. Baranku Boży... napełnij nas darami Ducha Świętego. Baranku Boży... rozpal w nas ogień miłości.' }
    ],
    mysteries: []
  },
  {
    id: 'modlitwy-poranne-pelne',
    name: 'Modlitwy poranne',
    category: 'inne',
    emoji: '',
    description: 'Kompletny zestaw modlitw na rozpoczęcie dnia. Pozwala uświęcić każdą chwilę nadchodzącego czasu.',
    history: 'Od wieków chrześcijanie zaczynali dzień od ofiarowania swoich trudów Bogu. Esencja polskiej pobożności.',
    intentions: ['uświęcenie dnia', 'bezpieczeństwo', 'rodzina'],
    duration: '7 min',
    days: null,
    intro: 'Boże, dziękuję Ci za noc dzisiejszą.',
    parts: [
      { title: 'Znak Krzyża', text: 'W imię Ojca i Syna, i Ducha Świętego. Amen.' },
      { title: 'Akt wiary', text: 'Wierzę w Ciebie, Boże żywy, w Trójcy jedyny prawdziwy. Wierzę, coś objawił Boże, Twe słowo mylić nie może.' },
      { title: 'Ofiarowanie dnia', text: 'Boże mój, ofiaruję Ci dzisiaj wszystkie moje modlitwy, prace, radości i cierpienia, w jedności z Ofiarą Jezusa Chrystusa na ołtarzu, dla uwielbienia Twego Imienia i dla zbawienia dusz.' },
      { title: 'Ojcze nasz', text: 'Ojcze nasz, któryś jest w niebie, święć się imię Twoje, przyjdź królestwo Twoje, bądź wola Twoja jako w niebie, tak i na ziemi. Chleba naszego powszedniego daj nam dzisiaj, i odpuść nam nasze winy, jako i mi odpuszczamy naszym winowajcom. I nie wódź nas na pokuszenie, ale nas zbaw ode złego. Amen.' },
      { title: 'Zdrowaś Maryjo', text: 'Zdrowaś Maryjo, łaski pełna, Pan z Tobą, błogosławionaś Ty między niewiastami i błogosławiony owoc żywota Twojego, Jezus. Święta Maryjo, Matko Boża, módl się za nami grzesznymi teraz i w godzinę śmierci naszej. Amen.' },
      { title: 'Aniele Boży', text: 'Aniele Boży, stróżu mój, Ty zawsze przy mnie stój. Rano, wieczór, we dnie, w nocy, bądź mi zawsze ku pomocy. Strzeż duszy, ciała mego i doprowadź mnie do żywota wiecznego. Amen.' }
    ],
    mysteries: []
  },
  {
    id: 'modlitwa-wieczorna',
    name: 'Modlitwy wieczorne',
    category: 'inne',
    emoji: '',
    description: 'Modlitwy na zakończenie dnia, obejmujące dziękczynienie i rachunek sumienia.',
    history: 'Zakorzenione w tradycji klasztornej (Kompleta), służą podsumowaniu dnia i powierzeniu się Bożej opiece.',
    intentions: ['wdzięczność', 'rachunek sumienia', 'spokojny sen'],
    duration: '5 min',
    days: null,
    intro: 'Spokojne zakończenie dnia w obecności Bożej.',
    parts: [
      { title: 'Znak Krzyża', text: 'W imię Ojca i Syna, i Ducha Świętego. Amen.' },
      { title: 'Dziękczynienie', text: 'Dziękuję Ci, Boże mój, żeś mnie dzisiaj stworzył, zachował i łaską swoją wspierał. Dziękuję Ci za wszystkie dobrodziejstwa dzisiejszego dnia.' },
      { title: 'Rachunek sumienia', text: 'Przypomnij sobie swoje dzisiejsze myśli, słowa, uczynki i zaniedbania. Czy kochałeś Boga nade wszystko? Czy byłeś miłosierny dla bliźnich?' },
      { title: 'Akt żalu', text: 'Ach, żałuję za me złości jedynie dla Twej miłości. Bądź miłościw mnie grzesznemu, do poprawy dążącemu.' },
      { title: 'Pod Twoją obronę', text: 'Pod Twoją obronę uciekamy się, święta Boża Rodzicielko, naszymi prośbami racz nie gardzić w potrzebach naszych, ale od wszelakich złych przygód racz nas zawsze wybawiać, Panno chwalebna i błogosławiona. Amen.' },
      { title: 'Modlitwa o spokojny sen', text: 'W ręce Twoje, Panie, polecam ducha mojego. Strzeż nas, Panie, jak źrenicy oka, w cieniu Twych skrzydeł ukryj nas. Amen.' }
    ],
    mysteries: []
  },
  {
    id: 'michal-ochrona',
    name: 'Modlitwa do św. Michała Archanioła',
    category: 'inne',
    emoji: '',
    description: 'Potężna modlitwa o ochronę przed wpływem zła i walkę duchową.',
    history: 'Zatwierdzona przez papieża Leona XIII.',
    intentions: ['ochrona', 'walka duchowa', 'bezpieczeństwo'],
    duration: '1 min',
    days: null,
    intro: 'Święty Michale Archaniele, broń nas w walce.',
    parts: [
      { title: 'Modlitwa', text: 'Święty Michale Archaniele, wspomagaj nas w walce, a przeciw niegodziwości i zasadzkom złego ducha bądź naszą obroną. Oby go Bóg pogromić raczył, pokornie o to prosimy, a Ty, Wodzu niebieskich zastępów, szatana i inne duchy złe, które na zgubę dusz ludzkich po tym świecie krążą, mocą Bożą strąć do piekła. Amen.' }
    ],
    mysteries: []
  },
  {
    id: 'peregryn-choroba',
    name: 'Modlitwa do św. Peregryna',
    category: 'inne',
    emoji: '',
    description: 'Patron chorych na raka i choroby ciężkie.',
    history: 'Św. Peregryn Laziosi sam został uzdrowiony z nowotworu nogi.',
    intentions: ['zdrowie', 'rak', 'operacja'],
    duration: '5 min',
    days: null,
    intro: 'Święty Peregrynie, uproś nam łaskę zdrowia.',
    parts: [
      { title: 'Modlitwa', text: 'O święty Peregrynie, Ty, któryś sam doświadczył cierpienia i cudownego uzdrowienia, wstaw się za nami u Pana. Uproś nam siłę do niesienia krzyża i przywróć zdrowie tym, którzy z wiarą o to proszą. Amen.' }
    ],
    mysteries: []
  }
]

export const CATEGORIES = [
  { id: 'all', label: 'Wszystkie', emoji: '' },
  { id: 'rozaniec', label: 'Różaniec', emoji: '' },
  { id: 'koronka', label: 'Koronka', emoji: '' },
  { id: 'maryjna', label: 'Maryjna', emoji: '' },
  { id: 'litania', label: 'Litania', emoji: '' },
  { id: 'nowenna', label: 'Nowenna', emoji: '' },
  { id: 'pasja', label: 'Pasja', emoji: '' },
  { id: 'liturgia-godzin', label: 'Liturgia Godzin', emoji: '' },
  { id: 'inne', label: 'Inne / Codzienne', emoji: '' },
]
